version: '3'
services:
  web:
    build:
      context: .
      args:
        jar: 'build/libs/census31-fwmt-job-service-27.0.0.jar'
    depends_on:
      - postgres
      - rabbitRM
      - rabbitGW
    ports:
      - '8025:8025'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres/postgres?currentSchema=fwmtg'
      SPRING_DATASOURCE_PASSWORD: 'password'
      SPRING_LIQUIBASE_URL: 'jdbc:postgresql://postgres/postgres?currentSchema=fwmtg'
      SPRING_LIQUIBASE_PASSWORD: 'password'
      RABBITMQ_HOSTNAME: 'rabbitmq'
      FEATURE_HH_CREATE: '${FEATURE_HH_CREATE:-false}'
      FEATURE_HH_UPDATE: '${FEATURE_HH_UPDATE:-false}'
      FEATURE_HH_CANCEL: '${FEATURE_HH_CANCEL:-false}'
      FEATURE_HH_PAUSE: '${FEATURE_HH_PAUSE:-false}'
      FEATURE_CE_CREATE: '${FEATURE_CE_CREATE:-false}'
      FEATURE_CE_UPDATE: '${FEATURE_CE_UPDATE:-false}'
      FEATURE_CE_CANCEL: '${FEATURE_CE_CANCEL:-false}'
      FEATURE_CE_SWITCH_CE_TYPE: '${FEATURE_CE_SWITCH_CE_TYPE:-false}'
      FEATURE_SPG_CREATE: '${FEATURE_SPG_CREATE:-false}'
      FEATURE_SPG_UPDATE: '${FEATURE_SPG_UPDATE:-false}'
      FEATURE_SPG_CANCEL: '${FEATURE_SPG_CANCEL:-false}'
      FEATURE_CCS_CREATE: '${FEATURE_CCS_CREATE:-false}'
      FEATURE_CCS_CANCEL: '${FEATURE_CCS_CANCEL:-false}'
      FEATURE_NC_CREATE: '${FEATURE_NC_CREATE:-false}'
      FEATURE_NC_CANCEL: '${FEATURE_NC_CANCEL:-false}'
  postgres:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
  rabbitRM:
    image: rabbitmq:3-management-alpine
    container_name: rabbitRM
    ports:
      - 5672:5672
      - 15672:15672
  rabbitGW:
    image: rabbitmq:3-management-alpine
    container_name: rabbitGW
    ports:
      - 5673:5672
      - 15673:15672
