apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  labels:
    app: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: job-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080